var alivenow=alivenow||{};

alivenow.Global={
    game:null,
    rotateHandler:null,
    skipRotationHandle:false,
    config:null,
    viewport:"portrait",
    challengeScore:0,
    currentView:null,
    gameWidth:768,
    gameHeight:1100,
    msecond:"00",
    second:"00",
    minute:"00",
    msecondStr:"",
    secondStr:"",
    minuteStr:"",
    startTime:0,
    elapsedTime:0,
    viewInFullScreen:false,
    gameStart:false,
    formSubmitted:false,
    gameScore:0,
    introShown:false,
    mode:"portrait",
    isIOS:false,
    hitPointSet:false,
    U_ID:null,
    gender:"male",
    gameKey:"",
    adSet:false,
    replayCount:0,
     URL_DATA:"./data.php",
    URL_CREATE:"./create.php",
    URL_UPDATE:"./valueUpdator.php",
    URL_LEADER:"./getLeaderData.php",
      URL_TSHARE_WEB : 'https://twitter.com/intent/tweet?text=Congratulations! You have completed the JIGSAW PUZZLE!&url=http://bit.ly/1WsQYsI',
    URL_FSHARE_WEB : 'https://www.facebook.com/sharer/sharer.php?u=http://bit.ly/1WsQYsI&t=Congratulations! You have completed the JIGSAW PUZZLE!'

};